AWSTemplateFormatVersion: 2010-09-09
Description: 
build roman numerals application
  
Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
  InstanceTypes:
    Description: EC2 instance types
    Type: String
    AllowedValues:
        - t2.micro
        - t2.small
        - t2.medium
        - t2.large
    Default: t2.micro
  Keypair:
    Description: Keypair for EC2 instance
    Type: AWS::EC2::KeyPair::KeyName
  
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP and SSH" # Required
      GroupName: "HTTPandSSH"
      SecurityGroupIngress: 
        - Description: "Allow HTTP"
          CidrIp: "0.0.0.0/0"
          ToPort: "80"          
          FromPort: "80"
          IpProtocol: "TCP"
        - Description: "Allow SSH"
          CidrIp: "0.0.0.0/0"
          ToPort: "22"          
          FromPort: "22"
          IpProtocol: "TCP"
          
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceTypes
      KeyName: !Ref Keypair
      SecurityGroupIds: 
        - !GetAtt WebServerSecurityGroup.GroupId
      UserData: "String"
      Tags: 
        - Key: Name
          Value: roman-numerals-webserver
  
#Outputs: